### PR TITLE
Remove checkpoints from lesson dir

### PR DESCRIPTION
**Pull request by impactmass**

### CODE REVIEW

**Comment by angelsvirkov** [comment]
GJ @impactmass, let's go ahead and follow the new concept

**Comment by impactmass** [comment]
> What are the next steps?

I need to write two guides. For teachers: "How to create checkpoints with the new structure". For students: "How to find checkpoints". I will do that later today.

**Comment by impactmass** [comment]
I added the guides in the repo Readme.

**Review by angelsvirkov — APPROVED** [review]
@impactmass , the explanation seems reasonable to me. PR is approved. Up to you to merge it if there is nothing else to add to the PR.

Maybe one question, how do we resolve the case for [Lesson 6](https://redi-school.github.io/nrw-html-and-css-2021-spring/lesson6/#html-tags-3) which has no dedicated stuff added to the checkpoint? Do we simply copy paste the files

**Comment by impactmass** [comment]
Hi @angelsvirkov. I'm ready to merge this now. I've updated the branch to apply changes on updated master. And created checkpoint10 branch.


PS: about this:
> how do we resolve the case for Lesson 6 which has no dedicated stuff added to the checkpoint

I think we can1 leave it for now. No checkpoint for lesson6. Checkpoint 7 should be compared to Checkpoint 5.

**Review by angelsvirkov — APPROVED** [review]
Looks good. Thanks for the huge effort here 💯

**Pull request merged**
