### PR TITLE
Lesson 11 added

### PR DESCRIPTION
**Pull request by vickjoeobi**
I created the lecture for lesson 11. Please review and approve.

### CODE REVIEW

**Review by angelsvirkov — COMMENTED** [review]
I did a first high level review of the content. I think section 1 and 3 are a good fit. I am not sure about section 2 though. It makes sense to some extent but it also might be more appropriate for later lessons unless you can directly say where we can include it in the checkpoints.

Another thing is the timing. The total sum is 85 mins , whereas a class has around 105 min active time. Should we add some more content or did you plan something more todo

I would also like to here other people's opinion. Once we align on the content I

**Comment by vickjoeobi** [comment]
You are right about the timing, I did not review the timing properly. The content alone is already fully fit for one full day of 180 mins, inclusive of break. I would review the timing and resubmit. 

Also, I think the second topic is important given that "Icons" are an important element used in designs.

**Comment by impactmass** [comment]
Good work @vickjoeobi.

I have a suggestion as I look at the overall flow of the CSS course. Here's my rough overview of what we have right now:

- Lesson 8:   Introduction: Syntax, Selectors Pt 1
- Lesson 9:   Selectors Pt 2, Styling Text Pt 1
- Lesson 10:  CSS units, Styling Text Pt 2, CSS Box Model 

You notice we have **Styling Text** 1 and 2.

I think Styling **Links** and **Lists**, goes well with **Styling Text**. I think we should do them before CSS Box Model. So that we do not jump back to Styling Text right after talking about the Box Model. 

I think once we start Box Model, we should then move into styles that are "*done on the Box*" e.g CSS Backgrounds, then after that, we can do Intro CSS Layouts. 

I am trying to remember why we added CSS Box Model into Lesson 10 (@angelsvirkov do you remember?). Maybe we were worried about spending too much time on **Styling Text** section?

Anyway, I think we should rearrange like this:

- Lesson 8:   Introduction: Syntax, Selectors Pt 1
- Lesson 9:   Selectors Pt 2, Styling Text Pt 1
- Lesson 10:  CSS units, Styling Text Pt 2, Styling Links and Lists
- Lesson 11:  CSS Box Model etc

cc @neyoalao: Good time to check if you already have topics in mind for Lesson 11.

Also, I think CSS Icons can also come in later class.

So, @vickjoeobi @angelsvirkov @otaruMendez what do you think about all this?

**Comment by angelsvirkov** [comment]
> Good work @vickjoeobi.
> 
> I have a suggestion as I look at the overall flow of the CSS course. Here's my rough overview of what we have right now:
> 
> * Lesson 8:   Introduction: Syntax, Selectors Pt 1
> * Lesson 9:   Selectors Pt 2, Styling Text Pt 1
> * Lesson 10:  CSS units, Styling Text Pt 2, CSS Box Model
>  ...
> Also, I think CSS Icons can also come in later class.
> 
> So, @vickjoeobi @angelsvirkov @otaruMendez what do you think about all this?

@impactmass , thanks for the thorough analysis here. I thought a little bit about what you suggest and I can agree with that. So I am totally up for the rearrangement. Regarding the reason for adding css box model there, it is because a lot of styling and rules touch upon the box model or would at least require to have some styles there, so we wanted to give us a bigger surface for practical styles that provide real joy to students. One minor improvement to lesson 10 you suggested Seun is the following. I believe CSS Units belong together with the Box Model so I would rather have lesson 11 = Units + Box model. And leave lesson 10 = Styling, text, links, and lists and maybe something else if there is time

**Comment by vickjoeobi** [comment]
Hello @impactmass, i think you might be right. But don't you think it would be too much of a work and "back and forth" if after preparing a lesson, i would have to always go back and start afresh. 

I would suggest that we generate topics for all the remaining classes, and then lectures can be prepared in that regards. If i had an initial lesson topic plan, it would aid for faster and more direct approach to lesson preparations. 

We could put this into consideration in our next taskforce sitting. 

Vincent

**Comment by impactmass** [comment]
Thanks Angel, I will take a few mins to review your suggestion above.

> don't you think it would be too much of a work and "back and forth" if after preparing a lesson, i would have to always go back and start afresh.

Hey @vickjoeobi, yes, I share your concern too. I actually thought about it before suggesting the change. You don't have to start afresh at all. We are only taking the content you have prepared and moving it around a bit. We should not delete what you've done. 

> I would suggest that we generate topics for all the remaining classes, and then lectures can be prepared in that regards. If i had an initial lesson topic plan, it would aid for faster and more direct approach to lesson preparations.

Your observation here is also correct. The discussion we are having on this PR was usually done in our meetings/calls. And there we are able to clear them out faster. This is is not the norm. In our meetings we try to generate and debate the topics. This PR approach happened as we have new teachers available for the Task Force after our usual meeting. Let's discuss this further on the call on Tuesday.

**Comment by impactmass** [comment]
OK, I like the suggestion. Here's what it looks like:

- Lesson 8:   Introduction: Syntax, Selectors Pt 1
- Lesson 9:   Colors, Selectors Pt 2, Styling Text Pt 1 (alignment, indent, shadow, font-family)
- Lesson 10:  Styling Text Pt 2 (Font Sizing), Styling Links (Link states etc), Styling Lists
- Lesson 11:  CSS Units, Setting Height & Width, CSS Box Model 

More feedback welcome. We should finalize on latest Tuesday.

**Comment by neyoalao** [comment]
Just wondering. Is everyone on board with the topics and I can go ahead with session 12? I have an hunch to wait to wait until after the meeting on Tuesday!

**Comment by impactmass** [comment]
@neyoalao what ideas have you considered for lesson 12 so far?

**Comment by angelsvirkov** [comment]
@vickjoeobi the latest decisions for Lesson 11 have been to turn it into Lesson 10 and to have the following content, as agreed during the task force meeting
```
# Lesson 10

### 1. CSS Link styling

ETA: 50min

## 2. CSS Lists styling

ETA: 50min
```

**Comment by vickjoeobi** [comment]
> - Lesson 11:  CSS Units, Setting Height & Width, CSS Box Model 


    I will edit it and resubmit ☺️

**Comment by vickjoeobi** [comment]
> @vickjoeobi the latest decisions for Lesson 11 have been to turn it into Lesson 10 and to have the following content, as agreed during the task force meeting
> 
> ```
> # Lesson 10
> 
> ### 1. CSS Link styling
> 
> ETA: 50min
> 
> ## 2. CSS Lists styling
> 
> ETA: 50min
> ```

Dear @angelsvirkov Does this mean I am now writing the notes for lesson 10 instead of 11? 

Please clarify.

**Comment by angelsvirkov** [comment]
> > @vickjoeobi the latest decisions for Lesson 11 have been to turn it into Lesson 10 and to have the following content, as agreed during the task force meeting
> > ```
> > # Lesson 10
> > 
> > ### 1. CSS Link styling
> > 
> > ETA: 50min
> > 
> > ## 2. CSS Lists styling
> > 
> > ETA: 50min
> > ```
> 
> Dear @angelsvirkov Does this mean I am now writing the notes for lesson 10 instead of 11?
> 
> Please clarify.

@vickjoeobi , yes you are writing the notes for lesson 10. It can also be seen in our message in MS teams

**Comment by vickjoeobi** [comment]
Nice, I looked out for the message but didn't see it yet. 

Thanks for the update.

**Comment by vickjoeobi** [comment]
Closed

**Pull request closed without merging**
