### PR TITLE
Add initial templates for lessons 9-12

### PR DESCRIPTION
**Pull request by angelsvirkov**
@otaruMendez , @impactmass  let's starting adding some ideas to the class agenda for 9-12 whenever we find time

### CODE REVIEW

**Comment by angelsvirkov** [comment]
Idea: I think we can have somewhere along sessions 9-12 a full or half lecture for debugging code via the Chrome debugger tools. This is would be particularly useful after students start writing some CSS but before they do complex CSS which often requires careful debugger tool inspection

**Comment by angelsvirkov** [comment]
Content Proposal for lesson 8 (Intro to CSS) - (although not part of this PR)
We can follow the [W3Schools CSS Tutorial](https://www.w3schools.com/css/default.asp) which I find good enough

1. Recap of CSS Intro (from [lesson 2](https://redi-school.github.io/nrw-html-and-css-2021-spring/lesson2/#2-introduction-to-css)) -> ETA: 10mins
2. CSS Syntax -> ETA 10-15min
3. CSS Selectors I -> ETA 40 min
 -  Categorization of the different selector groups as per W3S
 -  Teaching Students the simple CSS Selector group (first of the five) as shown [here](https://www.w3schools.com/css/css_selectors.asp) . That includes (element, class, id, universal and grouping selectors)
 
 > My idea is that in some other lesson down the course we have a section called `CSS Selectors ||` which covers advanced CSS Selectors (the rest 4 out of 5 groups)
 4. How to add CSS to HTML -> ETA 40 mins
 - explaining the different ways to add css as per [W3S](https://www.w3schools.com/css/css_howto.asp) and also provide the differences / pros and cons
 - Teach the cascading order? What is the CSS Specificity order? 
 - Also what happens if two identical css rules (with different values) are applied to the same one. 
 
 Exercise:
 - PRactice adding CSS to html via the different selectors and via the different integration methods. Students should not learn about CSS rules in this course, they should rather use a simple `{background: red}` rule, for example to learn selectors and html integration
 
 Homework:
 - We can ask them to use one inline, one class , one element, one id class and so on in their CV (with background red). We can again show them an image of what we want to achieve

**Comment by impactmass** [comment]
@angelsvirkov I think we should create a PR for lesson 8, and already put your suggestion in there as the content. We then discuss further on the PR

**Comment by angelsvirkov** [comment]
> @angelsvirkov I think we should create a PR for lesson 8, and already put your suggestion in there as the content. We then discuss further on the PR

On it 🦖

**Comment by otaruMendez** [comment]
Dropping the list of topics we can cover for CSS here:

- Formatting text with CSS - We discuss how to format texts on your webpage (font, font-height, font-size, font-style, font-weight, line-height, letter-spacing, word-spacing, text-align, text-shadow ... properties)

- The CSS Box Model - What is the Box Model?, Block and Inline blocks, Inner and Outer display types, Margins, padding and borders. [Reference](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model)

- Layout with Flexbox - Understanding flexbox (container & items), flexbox properties (flex-wrap, flex-directions, flex-flow, justify-content, flex-shrink, flex-grow etc.)

- Layout Essentials  - Layout with Position (absolute, fixed, relative), Layout with floats (float images, float layouts & clearing floats)

- Media Queries

**Comment by impactmass** [comment]
Lesson 9

CSS Selectors 2 

CSS Combinators
- Descendant selector (space)

ETA: 10mins

CSS Comments
- starts with /* and ends with */

ETA: 10mins

CSS Colors

CSS Color names
- e.g Tomato

Explain apllying colors using the following rules:
- Background Color
- Text Color
- Border Color

ETA: 20 mins


Formatting Text with CSS

- Text Alignment (`text-align`)
- Text Direction 
- Vertical Alignment
- Text Shadow (beware: don't overuse text shadows on your websites)
- Text Decoration
- Text Indentation

ETA: 30 mins (Give enough time for students to practice)

1hr 30mins (plus 10 mins brk)


CSS Fonts
- Font Families
- Web Safe Fonts and Font Fallback
- Font style (font-style)

ETA: 30 mins

Checkpoint: 
- Apply font to you page
- Text align on the footer


----------------


Lesson 10

CSS Units (or Measurement)
https://www.w3schools.com/css/css_units.asp
- px 
- em 
- rem
- %
TODO: Decided on list of units that we want to cover.


CSS Font Size
`font-size` - using some of the units


CSS Height & Width
- cover sizing with units
- cover sizing with non-numeric CSS values (e.g auto)


ETA: 50 mins

The CSS Box Model

- Task force TODO: Write an outline of what we need to teach here
- Read [this](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model) and [this](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Introduction_to_the_CSS_box_model)
- Basic understanding of the Elements Tab in the Dev Tools.

50 mins

**Comment by angelsvirkov** [comment]
@otaruMendez , the content for lesson 10 has been moved to lesson 11 and slightly updated to the following 

```
# Lesson 11

CSS Units (or Measurement)
https://www.w3schools.com/css/css_units.asp

- px
- em
- rem
- %
  TODO: Decided on list of units that we want to cover.

ETA: 50min

CSS Font Size
`font-size` - using some of the units

ETA: 15min

CSS Height & Width

- cover sizing with units
- cover sizing with non-numeric CSS values (e.g auto)

ETA: 30 mins

CSS Max-width (difference between width)
https://www.w3schools.com/css/css_max-width.asp

ETA: 15min
```

**Comment by angelsvirkov** [comment]
Lesson 12 is changed to the following

```
# Lesson 12 The CSS Box Model (move to separate)

- general overview of how box model looks
- Cover basics `margin padding border` as a whole
- Teach the basic parts individually

  - margin
  - padding
  - border

- Alternative CSS Box model
- with box-sizing
  https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model#the_alternative_css_box_model
- By how to inspect my box model in the browser

```

**Comment by angelsvirkov** [comment]
@impactmass , @otaruMendez , @neyoalao , @vickjoeobi I am closing this PR since we have nothing more to discuss for lessons 9-12 on a such high level. The individual discussions have been moved to new PRs
- Lesson 10 - #34 
- Lesson 11 - TODO (fyi @otaruMendez )
- Lesson 12 - TODO (by me - Angel)
- Lesson 13 - #37 
- Lesson 14 + other topics - #31

**Pull request closed without merging**
