### PR TITLE
Checkpoint22

### PR DESCRIPTION
**Pull request by angelsvirkov**
@impactmass I have added the CSS Icons and URL Fragment content to lesson22. Together with that I have added checkpoint 22 for these things. I am not sure how much more time we have in this lecture. Maybe we could add something more like a background image to checkpoint22 and that should be it I guess

### CODE REVIEW

**Comment by angelsvirkov** [comment]
https://user-images.githubusercontent.com/18263878/121806719-537c3b80-cc51-11eb-9ee7-91aced1cce6b.mp4

**Comment by impactmass** [comment]
Thanks for starting this PR 👍 . I think with the two exercises, and some time for questions, we have enough for the class. And if possible we can also help anyone struggling to use bg-images on their project. 

PS: Since I only created checkpoint21 branch after you started this PR, I have just updated the base branch here. I also made a few changes to match the additions in checkpoint21.

**Comment by angelsvirkov** [comment]
> Thanks for starting this PR 👍 . I think with the two exercises, and some time for questions, we have enough for the class. And if possible we can also help anyone struggling to use bg-images on their project.
> 
> PS: Since I only created checkpoint21 branch after you started this PR, I have just updated the base branch here. I also made a few changes to match the additions in checkpoint21.

Thank you for doing this.

**Comment by angelsvirkov** [comment]
Closing PR as we have nothing more to add here and this is a checkpoint PR

**Pull request closed without merging**
