### PR TITLE
Add initial ProgressMonitoring docs

### PR DESCRIPTION
**Pull request by angelsvirkov**
@otaruMendez @impactmass @neyoalao @vickjoeobi, here is the document where we would like to define a concrete procedure on how to monitor the student progress on their personal portfolio websites.

We need to cover the following topics:
- [x] 1. Is it decided that we use CodeSandbox? Are there any other suggestions?
- [x] 2. When and how much do we check student progress?
- [x] 3. How do we give feedback to students ?
- [x] 4. How does the synchronization between CodeSandBox and VS Code work? Maybe there is a plugin to facilitate that?
- [x] 5. _Updated:_ Anything else. Should we make every checkpoint in a separate folder / codesandbox as described [here](https://github.com/ReDI-School/nrw-html-and-css-2021-spring/pull/32#issuecomment-821945014)?
- [ ] 6. After discussing 1-5, we need to document the concept in the given md file for future reference.

### CODE REVIEW

**Comment by vickjoeobi** [comment]
> @otaruMendez @impactmass @neyoalao @vickjoeobi, here is the document where we would like to define a concrete procedure on how to monitor the student progress on their personal portfolio websites.
> 
> We need to cover the following topics:
> 
> * [ ]  1. Is it decided that we use CodeSandbox? Are there any other suggestions?
I think, for now, CodeSandbox is the best alternative solution to the GitHub classroom.
> * [ ]  2. When and how much do we check student progress?
The progress needs to be checked weekly. By this, I mean that the two classes for the week i.e The Tuesday and Thursday class needs to have some sort of synchronization. The deadline could be given for either Saturday or Sunday  23:55. This way the teachers can have time to grade the students and give feedback. The grading system is to be decided by the teachers. 
> * [ ]  3. How do we give feedback to students?
It could be two ways: 1. The teachers that taught the class and gave the assignment giving the feedback or we can divide the students and give feedback to students that fall in our category. 
> * [ ]  4. How does the synchronization between CodeSandBox and VS Code work? Maybe there is a plugin to facilitate that?
Yes, i just looked up and observed that there is a plugin that can work with this. I feel we all should individually test it out to be able to determine the working method, thereby making it easy for us to teach the students and help them when they have problems. 
> * [ ]  5. Anything else that we have not gone thoroughly thought about?
> * [ ]  6. After discussing 1-5, we need to document the concept in the given md file for future reference.

##Find my response inline.

**Comment by impactmass** [comment]
> Yes, i just looked up and observed that there is a plugin that can work with this. I feel we all should individually test it out to be able to determine the working method, thereby making it easy for us to teach the students and help them when they have problems.

Hey @vickjoeobi, please can you share a link to the plugin you found. I searched and can't find it

**Comment by impactmass** [comment]
Thanks Angel. These are good questions to help guide the decision.

> Is it decided that we use CodeSandbox? Are there any other suggestions?

I think CodeSandbox is fine for us becase we do not have to do a lot of setup. That is a good thing due to our time constraint. We've already shown them CodeSandbox and they just write their tasks there.

> When and how much do we check student progress?

Once a week. Preferably weekend. We rotate the teacher(s) that will look at the CodeSandboxes. They should not spend elaborate time on each. They just need to check the student's work against the checkpoint.

> How do we give feedback to students ?

I'll prefer we keep it simple. A simple MS document should be created (one for each student). The teacher writes comments in there. We grant individual students access to the document. If a student needs further clarification/help about a comment in the doc, s/he can request.

> How does the synchronization between CodeSandBox and VS Code work? Maybe there is a plugin to facilitate that?

I have not found a way to synchronization the two. I will stick with manual copy for now. Let's keep this idea as slim as possible. This is a pilot. If we see that it's working, we can invest in making the setup better.

**Comment by angelsvirkov** [comment]
Here are my 2 cents, as well:

>  1. Is it decided that we use CodeSandbox? Are there any other suggestions?
To me this is a good suggestion for now. In future we can try GH Classrooms.

> 2. When and how much do we check student progress?
I would also say once a week is enough. That means we need to have maybe a new concept of the Weekly Feedback Master. It might make sense that this teacher (the feedback master) enters their readiness in the Excel Organizational Sheet. Do we want to address this topic to ReDI Coordiantors?

> 3. How do we give feedback to students ?
A shared document in MS Teams for each student is a good idea. Regarding the grading, I would go against it, because the purpose of the feedback is to teach student and not compare them to anything.

> 4. How does the synchronization between CodeSandBox and VS Code work? Maybe there is a plugin to facilitate that?
There is indeed a [plugin](https://github.com/yesmeck/vs-codesandbox), but it looks rather unmaintained and buggy to me. Maybe I can check it but we could also stick to plain copy-pasting for now.

> 5. Anything else that we have not went thoroughly thought about?
Should we make students create separate folders or separate CodeSandboxes for each checkpoint. E.g. Ahmed-Checkpoint-9, so that we can see what is the last working version and thus easily maybe give feedback on what has changed or created a new bug. We can also make students to have one folder per checkpoint

> 6. After discussing 1-5, we need to document the concept in the given md file for future reference.
Are you guys up for documenting the approach?

**Comment by impactmass** [comment]
> because the purpose of the feedback is to teach student and not compare them to anything.

please explain further what you mean here? Do you mean we shouldn't compare what they've submitted to the checkpoints?  What is your idea of what the students should submit?

**Comment by angelsvirkov** [comment]
> > because the purpose of the feedback is to teach student and not compare them to anything.
> 
> please explain further what you mean here? Do you mean we shouldn't compare what they've submitted to the checkpoints? What is your idea of what the students should submit?

Vincent said ` This way the teachers can have time to grade the students and give feedback. The grading system is to be decided by the teachers.` . To that, I gave my counter arguments, which are agains introducing a grading system. Because the grading system compares students against each other and against some scale, which I would not want to have.

We can simply give feedback to what they have submitted and compare their work against the corresponding checkpoints. But I vote against any grading system. 

Does this help you now?

**Comment by impactmass** [comment]
> Does this help you now?

yes, I get you now. And +1 from me on what you said.

**Comment by otaruMendez** [comment]
I like the idea, I already saw some students sites differ from what we expect from the checkpoints, this will help put everyone back on track. 

Here is what I think on the questions:

>Is it decided that we use CodeSandbox? Are there any other suggestions?

Sounds good to me

> When and how much do we check student progress?

When: I would prefer we use the time slot for one of the lecture days (Tuesday or Thursday). I think having an additional day/time-slot will be going against what everyone signed up for (both teachers and students)

How often: after every 4 lectures

>How do we give feedback to students ?

Instant feedback in live breakout session with the teachers, we could use the breakout rooms feature in teams (I think) to split the students and share the load among the teachers

**Comment by angelsvirkov** [comment]
I think we have had some time now to think about all points. So I would try to summarize

>  1. Is it decided that we use CodeSandbox

 Everyone agrees to use CodeSandbox
 
 > 2. When and how much do we check student progress?
 
 3 people (Vincent, Seun and I) are for a weekly check and 1 person (Babatunde) is for bi-weekly checks. Following a democratic approach I would say we decide on a weekly feedback which maybe happens after Thursday class but before weekend, so that Students have time to address the feedback on the weekend until next Tuesday. @otaruMendez , if you have strong arguments against a weekly approach, please express them now.
 
 > 3. How do we give feedback to students (what methodology / what instrument do we use) ?
 
 2 people (Seun and I) are for shared MS Documents which are written asynchronously. 1 person (Babatunde) is for giving feedback synchronously on live student meetings. 1 person (Vincent) has not expressed a detailed opinion on how to give feedback to students. Following the democratic approach, we can go for shared MS Documents in Teams. If @otaruMendez  or @vickjoeobi have strong arguments against this approach please express them now.
 
 
 > 4. How does the synchronization between CodeSandBox and VS Code work? Maybe there is a plugin to facilitate that?
 
 It looks like no one of us found a solid and convincing solution. I think we all agree to keep this simple for now and simply make students copy paste their local folders to codesandbox.
 
 > 5. Anything else that we have not went thoroughly thought about?
 
 It looks like there are no extra points express beside one minor point expressed by me. The point is about the necessity of making every checkpoint a separate folder (separate codesandbox). Please read more [here](https://github.com/ReDI-School/nrw-html-and-css-2021-spring/pull/32#issuecomment-821945014)
 
 > 6. After discussing 1-5, we need to document the concept in the given md file for future reference.
 
 @impactmass has expressed readiness to take this point.
 
 
 ---

**Comment by neyoalao** [comment]
> It looks like there are no extra points express besides one minor point expressed by me. The point is about the necessity of making every checkpoint a separate folder (separate codesandbox). Please read more here.
I am in support of creating different folders for the checkpoints in code sandbox. This will serve as a version control so to say!

**Comment by impactmass** [comment]
> Should we make students create separate folders or separate CodeSandboxes for each checkpoint. E.g. Ahmed-Checkpoint-9, so that we can see what is the last working version and thus easily maybe give feedback on what has changed or created a new bug. We can also make students to have one folder per checkpoint

Hmm, I don't really see the need to compare the student's last week submission to the current week's submission. I think that as long as the teacher knows what changes they are looking out for (which we have on GitHub), s/he just checks for that. e.g if you know that this week, some footer styles should have been applied, you just go ahead and check for that.

> I would prefer we use the time slot for one of the lecture days (Tuesday or Thursday). I think having an additional day/time-slot will be going against what everyone signed up for

Good point about the fact that this is additional work that for teachers. Maybe this will need to be done by the task force.

> weekly feedback which maybe happens after Thursday class but before weekend,

Maybe, deadline for students can be announced as Friday midnight. Sat, Sun for teachers to check.

**Comment by angelsvirkov** [comment]
@impactmass , I believe a separate folder per checkpoint can do no bad things, but only good things such as:
- Making sure teachers do not review same code twice (also easier for teachers to communicate what has been reviewed)
- Making students capture the state of their last working website
- Showing students the progress they are doing throughout the course

Following the democratic approach we have 3 votes (Babatunde, Olaniyi and me) for the checkpoint-folder-separation and 1 vote against (Seun). I also do not see strong arguments against that approach expressed by Seun. Therefore, I would say we go for this approach and move on.

If that is the case, then step 5 is resolved and we are left with step 6. Anyone wants to add something? Maybe the last detail is how to exactly schedule the feedback between Thursday and Tuesday

**Comment by vickjoeobi** [comment]
> > > because the purpose of the feedback is to teach student and not compare them to anything.
> > 
> > 
> > please explain further what you mean here? Do you mean we shouldn't compare what they've submitted to the checkpoints? What is your idea of what the students should submit?
> 
> Vincent said ` This way the teachers can have time to grade the students and give feedback. The grading system is to be decided by the teachers.` . To that, I gave my counter arguments, which are agains introducing a grading system. Because the grading system compares students against each other and against some scale, which I would not want to have.
> 
> We can simply give feedback to what they have submitted and compare their work against the corresponding checkpoints. But I vote against any grading system.
> 
> Does this help you now?

I meant feedback though... but i completely go with your suggestion.

**Comment by angelsvirkov** [comment]
Task force meeting update. We found couple of important points that are blocking us right now. See below:

### What are teachers actually doing?

Teachers should check whether students have managed to implement the checkpoint as expected. This should only be a top level review where we only focus on whether the student is managing to follow along the checkpoints. The teacher should not go into extra details.

> Goal is to answer: Is the checkpoint done or not?

### Who to review

Can only be found out after a proper discussion with Solène

### When to review exactly

Can only be found out after a proper discussion with Solène

**Comment by angelsvirkov** [comment]
Closing this PR due to lack of time and resources

**Pull request closed without merging**
